name: Actualizar Todos los Sensores

on:
  schedule:
    - cron: '0 6 * * *'  # Todos los días a las 06:00 UTC
  workflow_dispatch:      # Ejecución manual

permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install requests pandas

      - name: Ejecutar script del sensor 00:1F:94:03:06:CD
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python "00:1F:94:03:06:CD/script.py"

      - name: Ejecutar script del sensor 00:1F:94:03:06:CE
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python "00:1F:94:03:06:CE/script.py"

      - name: Ejecutar script del sensor 00:1F:94:03:06:D0
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python "00:1F:94:03:06:D0/script.py"

      - name: Ejecutar script del sensor 98:8B:AD:20:2E:72
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python "98:8B:AD:20:2E:72/script.py"

      - name: Ejecutar script del sensor 98:8B:AD:20:2E:7E
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python "98:8B:AD:20:2E:7E/script.py"

      - name: Guardar cambios en el repositorio
        run: |
          git config --global user.name "bot-actualizador"
          git config --global user.email "bot@actions.github.com"
          git add .
          git diff --staged --quiet || git commit -m "Actualización automática de todos los sensores"
          git push origin main
